<?php
// Searches for entries matching the search term across multiple fields.
function search($search) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DB_HOST . "; dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
            DB_USER,
            DB_PASS
        );

        // Search across all relevant fields using JOIN
        $select_query = "SELECT
            s.site_name,
            s.url,
            c.email,
            c.username,
            s.comment,
            u.first_name,
            u.last_name
        FROM sites s
        INNER JOIN credentials c ON s.site_id = c.site_id
        INNER JOIN users u ON s.user_id = u.user_id
        WHERE s.site_name LIKE :search
           OR s.url LIKE :search
           OR c.email LIKE :search
           OR c.username LIKE :search
           OR s.comment LIKE :search
           OR u.first_name LIKE :search
           OR u.last_name LIKE :search";

        $statement = $db->prepare($select_query);
        $search_param = "%{$search}%";
        $statement->execute(array('search' => $search_param));

        $results = $statement->fetchAll();

        if (count($results) == 0) {
            return 0;
        }

        echo "      <table>\n";
        echo "        <thead>\n";
        echo "          <tr>\n";
        echo "            <th>Site Name</th>\n";
        echo "            <th>URL</th>\n";
        echo "            <th>Email</th>\n";
        echo "            <th>Username</th>\n";
        echo "            <th>Comment</th>\n";
        echo "            <th>User</th>\n";
        echo "          </tr>\n";
        echo "        </thead>\n";
        echo "        <tbody>\n";

        foreach ($results as $row) {
            echo "          <tr>\n";
            echo "            <td>" . htmlspecialchars($row['site_name']) . "</td>\n";
            echo "            <td>" . htmlspecialchars($row['url']) . "</td>\n";
            echo "            <td>" . htmlspecialchars($row['email']) . "</td>\n";
            echo "            <td>" . htmlspecialchars($row['username']) . "</td>\n";
            echo "            <td>" . htmlspecialchars($row['comment']) . "</td>\n";
            echo "            <td>" . htmlspecialchars($row['first_name'] . ' ' . $row['last_name']) . "</td>\n";
            echo "          </tr>\n";
        }

        echo "        </tbody>\n";
        echo "      </table>\n";

        $statement = null;

    } catch(PDOException $e) {
        echo '<p class="highlight">The following message was generated by function <code>search</code>:</p>' . "\n";
        echo '<p class="error">' . htmlspecialchars($e->getMessage()) . '</p>' . "\n";
        echo '<p>Click <a href="./">here</a> to go back.</p>';
        exit;
    }
}

// Updates a site's information based on site name pattern match.
function updateSite($site_name, $new_url = null, $new_comment = null) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DB_HOST . "; dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
            DB_USER,
            DB_PASS
        );

        $updates = array();
        $params = array('site_name' => $site_name);

        if ($new_url !== null && $new_url !== '') {
            $updates[] = "url = :url";
            $params['url'] = $new_url;
        }

        if ($new_comment !== null && $new_comment !== '') {
            $updates[] = "comment = :comment";
            $params['comment'] = $new_comment;
        }

        if (empty($updates)) {
            return;
        }

        $update_query = "UPDATE sites SET " . implode(", ", $updates) . " WHERE site_name = :site_name";

        $statement = $db->prepare($update_query);
        $statement->execute($params);
        $statement = null;

    } catch(PDOException $e) {
        echo '<p class="highlight">The following message was generated by function <code>updateSite</code>:</p>' . "\n";
        echo '<p class="error">' . htmlspecialchars($e->getMessage()) . '</p>' . "\n";
        exit;
    }
}

//Updates credentials based on site name pattern match.
function updateCredentials($site_name, $new_email = null, $new_username = null, $new_password = null) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DB_HOST . "; dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
            DB_USER,
            DB_PASS
        );

        // First get the site_id
        $site_query = "SELECT site_id FROM sites WHERE site_name = :site_name";
        $site_stmt = $db->prepare($site_query);
        $site_stmt->execute(array('site_name' => $site_name));
        $site = $site_stmt->fetch();

        if (!$site) {
            return;
        }

        $site_id = $site['site_id'];
        $updates = array();
        $params = array('site_id' => $site_id);

        if ($new_email !== null && $new_email !== '') {
            $updates[] = "email = :email";
            $params['email'] = $new_email;
        }

        if ($new_username !== null && $new_username !== '') {
            $updates[] = "username = :username";
            $params['username'] = $new_username;
        }

        if ($new_password !== null && $new_password !== '') {
            // Generate new IV and encrypt password
            $db->exec("SET @key_str = UNHEX(SHA2('" . AES_KEY . "', 512))");
            $db->exec("SET @new_iv = RANDOM_BYTES(16)");

            $updates[] = "encrypted_password = AES_ENCRYPT(:password, @key_str, @new_iv)";
            $updates[] = "iv = @new_iv";
            $params['password'] = $new_password;
        }

        if (empty($updates)) {
            return;
        }

        $update_query = "UPDATE credentials SET " . implode(", ", $updates) . " WHERE site_id = :site_id";

        $statement = $db->prepare($update_query);
        $statement->execute($params);
        $statement = null;

    } catch(PDOException $e) {
        echo '<p class="highlight">The following message was generated by function <code>updateCredentials</code>:</p>' . "\n";
        echo '<p class="error">' . htmlspecialchars($e->getMessage()) . '</p>' . "\n";
        exit;
    }
}

// Inserts a new site and its credentials into the database.
function insert($site_name, $url, $email, $username, $password, $comment, $user_id = 1) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DB_HOST . "; dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
            DB_USER,
            DB_PASS
        );

        // Insert into sites table
        $site_query = "INSERT INTO sites (site_name, url, user_id, comment) VALUES (:site_name, :url, :user_id, :comment)";
        $site_stmt = $db->prepare($site_query);
        $site_stmt->execute(array(
            'site_name' => $site_name,
            'url' => $url,
            'user_id' => $user_id,
            'comment' => $comment
        ));

        $site_id = $db->lastInsertId();

        // Prepare encryption
        $db->exec("SET @key_str = UNHEX(SHA2('" . AES_KEY . "', 512))");
        $db->exec("SET @iv = RANDOM_BYTES(16)");

        // Insert into credentials table
        $cred_query = "INSERT INTO credentials (user_id, site_id, email, username, encrypted_password, iv)
                       VALUES (:user_id, :site_id, :email, :username, AES_ENCRYPT(:password, @key_str, @iv), @iv)";

        $cred_stmt = $db->prepare($cred_query);
        $cred_stmt->execute(array(
            'user_id' => $user_id,
            'site_id' => $site_id,
            'email' => $email,
            'username' => $username,
            'password' => $password
        ));

        $site_stmt = null;
        $cred_stmt = null;

    } catch(PDOException $e) {
        echo '<p class="highlight">The following message was generated by function <code>insert</code>:</p>' . "\n";
        echo '<p class="error">' . htmlspecialchars($e->getMessage()) . '</p>' . "\n";
        exit;
    }
}

//Deletes an entry based on site name pattern match.
function delete($site_name) {
    try {
        include_once "config.php";

        $db = new PDO(
            "mysql:host=" . DB_HOST . "; dbname=" . DB_NAME . ";charset=" . DB_CHARSET,
            DB_USER,
            DB_PASS
        );

        $delete_query = "DELETE FROM sites WHERE site_name = :site_name";
        $statement = $db->prepare($delete_query);
        $statement->execute(array('site_name' => $site_name));
        $statement = null;

    } catch(PDOException $e) {
        echo '<p class="highlight">The following message was generated by function <code>delete</code>:</p>' . "\n";
        echo '<p class="error">' . htmlspecialchars($e->getMessage()) . '</p>' . "\n";
        exit;
    }
}
